= 面试前必看
qcrao <qcrao91@gmail.com>
v0.1, 2020-01-27
:toc: left
:homepage: http://qcrao.com

这是一份面试前必须要看一遍的材料，非常重要，会持续更新。目的是梳理所有在面试过程中遇到的问题，要有总结。

为了避免给出的链接失效，我会先收藏网页到云笔记，再给出云笔记中的分享链接。一次完整的面试，包括面试前的充分准备、面试中的随时总结、面试后的 offer 选择。本文着重于面试前的准备，从技术和非技术两方面展开。面试中、面试后则会给出一些 tips。

持续收集大概率好文，但未精读，待总结：

https://mubu.com/doc6ilPZg9zY89[https://mubu.com/doc6ilPZg9zY89]

TIP: 面试中：

TIP: 面试后：

== 技术

=== 数据结构 && 算法

* https://www.evernote.com/shard/s659/sh/a750d92f-1427-4cc1-ad0d-adff53e6f745/672c57d36f4b86ca157e23d659f71352[二分法的变种]

根据返回元素的位置（第一个还是最后一个），决定返回 left 索引还是 right 索引；在中间缩小判断范围的过程中，则根据要求排除不符合的元素，缩小 left 或 right 的范围。

例如，找出最后一个与 key 相等的元素。

```c
int searchLastEqual(int *arr, int n, int key)
{
    int left = 0, right = n-1;
    while(left<=right) {
        int mid = (left+right)/2;
        if(arr[mid] > key) right = mid - 1;
        else if(arr[mid] <= key) left = mid + 1;
    }
    if( right >= 0 && arr[right] == key) return right;
    return -1;
}
```

要求最后一个相等，故返回 right 索引；中间进行判断的时候，将 key 与中间元素相比，如果中间元素大，则要移动 right 索引；最后，再判断 right 索引处的元素是否真的与 key 相等。

* 十大排序

=== Go 语言
* Go 为什么这么快？
* 聊聊 GPM？

=== 网络
* 三次握手、四次挥手

=== 操作系统
* 零拷贝是什么原理？
* fork 的流程？
* select/poll/epoll 的区别？

=== 数据库

==== redis/codis

==== mysql
* 事务的隔离级别有哪几种？

=== 中间件

==== etcd
==== nginx
==== lvs

=== 系统设计
* 微信群红包的设计
* 秒杀系统的设计
* 抖音播放量、点赞量的设计
* 朋友圈关注、粉丝的设计
* 断点续传功能设计

== 非技术

=== 一次准备，随时吹牛
* 你有什么优点，缺点？
* 项目里最成功的地方/失败的地方？
* 印象最深的一次 debug
* 这两年（上一家公司）有什么收获、成长？经验、教训？
* 你有什么问题需要问我的？

一面：当初来这里是怎么考虑的

二面：如果过来，会给我安排做什么方向；对这块的规划，有什么难点和挑战

三面：小组怎么分工，对前景的理解

HR：晋升体制、福利待遇、技术成长

=== 关于博客

面试前要过一遍内容，并且要自我回答如下几个问题：

. 为什么写博客？
. 对实际工作有什么帮助，例子？
. 读 Go 源码有什么收获，体会？
寻找开源软件的优点，不要盯着缺点，link:{https://mubu.com/document_image/f483a8db-3539-467c-acfd-eb0de11f3289-2793993.jpg}[caoz的梦呓]。比如曹大说的可以学到无锁化编程的技巧。
